#!/bin/sh /etc/rc.common

. /lib/functions/commotion.sh
. /lib/config/uci.sh

#DEBUG=echo
START=19
STOP=91

boot() {
  case "$(uci_get wireless @wifi-device[0] disabled 1)" in
    1)
      case "$(uci_get wireless @wifi-iface[0] ssid "OpenWrt")" in
        "OpenWrt")
          rm -f /etc/config/wireless
          $DEBUG /sbin/wifi detect > /etc/config/wireless
          # Clear out any existing wireless interfaces
          $DEBUG uci_load wireless
          while [ "$?" != '1' ]; do
            logger -t commotion.init "Removing interfaces."
            $DEBUG uci_remove wireless @wifi-iface[]
          done
          $DEBUG uci_commit wireless
          logger -t commotion.init "Applied wireless defaults."
        ;;
      esac
    ;;
  esac
  mkdir -m 0755 -p /var/run/commotion
  start
}

start() {
  local args bind profiles pid statedir id

  config_cb() {  
    local type="$1"
    local name="$2"
    
    case "$type" in
      "daemon")
      	option_cb() {
      	  local name="$1"
      	  local value="$2"
        
          case "$name" in
            "bind")
              append args "-b $value"
              ;;
            "profiles")
              append args "-f $value"
              ;;
            "pid")
              append args "-p $value"
              ;;
            "statedir")
              append args "-s $value"
              ;;
          esac
        }
        ;;
      "node")
      	option_cb() {
      	  local name="$1"
      	  local value="$2"
        
          case "$name" in
            "id")
              append args "-i $value"
              ;;
          esac
        }
        ;;
    esac
  }
  config_load commotiond

  $DEBUG service_start /usr/sbin/commotiond $args
  
  [ -z "$(uci_get commotiond @node[0] id)" ] && {
    echo "Nodeid generation!"
    commotion_set_nodeid_from_mac "$(cat /sys/class/ieee80211/phy0/macaddress)"
    uci_set commotiond @node[0] id "$(commotion_get_nodeid)"
    uci_commit commotiond
  }
  
  reset_cb
  local aname
  config_cb() {  
    local type="$1"
    local name="$2"
    aname=$name
    
    [ "$type" = "interface" ] && {
      	option_cb() {
      	  local option="$1"
      	  local value="$2"
        
          [ "$option" = "profile" ] && {
              local ifname="$(uci_get network $aname ifname)" 
              [ ! -z $ifname ] && {
                commotion_up $(uci_get network $aname ifname) $value 
                logger -s -t commotion-init "commotion_up $(uci_get network $aname ifname) $value"
              }
          }
        }
    }
  }
  config_load network

}

stop() {
  $DEBUG service_stop /usr/sbin/commotiond 
}
