#!/bin/sh
[ -f "/usr/bin/patch" ] && { \
  cd /etc/init.d/
  patch -p0 < /usr/share/commotion/patches/dnsmasq.patch
  
  cd /lib/wifi/
  patch -p0 < /usr/share/commotion/patches/mac80211.sh.patch
}

uci add ucitrack setup_wizard
uci set ucitrack.@setup_wizard[0].init='commotiond'
uci commit ucitrack

exit 0
