#!/bin/sh
[ -f "/usr/bin/patch" ] && { \
  cd /etc/init.d/
  patch -p0 < /usr/share/commotion/patches/dnsmasq.patch
  
  cd /lib/wifi/
  patch -p0 < /usr/share/commotion/patches/mac80211.sh.patch
}

[ -f "/etc/crontabs/root" ] || touch /etc/crontabs/root

grep -q "commotiond" /etc/crontabs/root || { \
  echo '* * * * *   /etc/init.d/commotiond cron' >> /etc/crontabs/root
  /etc/init.d/cron restart
}

uci add ucitrack setup_wizard
uci set ucitrack.@setup_wizard[0].init='commotiond'
uci commit ucitrack

exit 0
